package rpgboss.editor.map_generator
import scala.math.abs


/*
  Author: Asma Oualmakran
  Class: Container: constructs a container which is a subsection
                    of a canvas / game field
        parameters:
                  x: type -> Integer, the horizontal starting point of the canvas/field
                  y: type -> Integer, the vertical starting point of the canvas/field
                  h: type -> Integer, the horizontal end point of the canvas/field
                  w: type -> Integer, the vertical end point of the canvas/field
       Use: To subsection the game field or other subsections.
   case class is used, the data generated by the class is immutable.
 */


case class Container(x:Int, w:Int, y:Int, h:Int) extends Tcontainer {

  val leftBound = this.x
  val rightBound = this.w
  val upperBound = this.y
  val lowerBound = this.h
  val width = abs(rightBound - leftBound)
  val height = abs(lowerBound - upperBound)

  /*
    Function: point
    Parameters:
      x: Int
        Use: The x coordinate of the point.
      y: Int
        Use: The y coordinate of the point.
    Return: Tuple2[Int, Int]
    Use: Takes 2 integers and converts them to a tuple to use as coordinates.
   */
  override def point(x:Int, y:Int):Tuple2[Int, Int] ={
    if(x < rightBound && x > leftBound && y < lowerBound && y > upperBound){
      return (x,y)
    }else {
      sys.error("Point is out of range of the container")
    }
  }


  /*
    Function: size
    Parameters: n/a
    Returns: Int
    Use: Calculate the surface of the container.
   */

  override def size():Int = width*height

  /*
    Function: center
    Parameters: n/a
    Returns: Tuple2[Int, Int]
    Use: Calculate the center point of the container.
   */
  override def center():Tuple2[Int, Int] = ((width/2), (height/2))

}

